const NODE_ENV = process.env.NODE_ENV;
const NODE_ENV_IS_DEV = NODE_ENV === "development";

if (NODE_ENV_IS_DEV) {
    require("dotenv").config();
}

const swaggerAutogen = require("swagger-autogen")();

const doc = {
    info: {
        version: "1.0.0",
        title: "Aeolus API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: NODE_ENV_IS_DEV ? "localhost:8080" : "aeolus.se",
    basePath: NODE_ENV_IS_DEV ? "" : "/api",
    schemes: ["http", "https"],
    consumes: ["application/json"],
    produces: ["application/json"],
    tags: [
        {
            name: "User",
            description: "Endpoints"
        },
        {
            name: "Simulator",
            description: "It's a simulator..."
        }
    ],
    securityDefinitions: {
        apiKeyAuth: {
            type: "apiKey",
            in: "header", // can be "header", "query" or "cookie"
            name: "X-API-KEY", // name of the header, query parameter or cookie
            description: "any description..."
        }
    },
    definitions: {
        Household: {
            id: "61ad382463b9d0f48e4fab6b",
            owner: "9d598d69-c660-4085-b0aa-830106e3a09e",
            dashboard: [0, 2, 1, 3, 6, 4, 5],
            thumbnail: "myImage.jpg",
            area: 12,
            location: {
                latitude: 65.61788868204044,
                longitude: 22.13848008165606
            },
            blackout: false,
            baseConsumption: 500,
            heatingEfficiency: 0,
            battery: {
                maxCapacity: 1000000
            },
            sellRatioOverProduction: 0.5,
            buyRatioUnderProduction: 0.6,
            windTurbines: {
                active: 3,
                maximumProduction: 3500,
                cutinWindspeed: 3,
                cutoutWindspeed: 25
            },
            consumptionSpike: {
                AmplitudeMean: 2300,
                AmplitudeVariance: 300,
                DurationMean: 35,
                DurationVariance: 10
            }
        }
    }
};

if (process.env.SWAGGER_FILE === undefined) {
    throw new Error(
        "Swagger outputfile cannot be undefined. Please specify a value to the enviroment variable 'SWAGGER_FILE'."
    );
}

const outputFile = `./dist/${process.env.SWAGGER_FILE}`;
const endpointsFiles = ["./dist/routes/*.js"];

console.log(`outputfile is: "${outputFile}"`);

swaggerAutogen(outputFile, endpointsFiles, doc);
