if (process.env.NODE_ENV === "development") {
    require("dotenv").config();
}

const swaggerAutogen = require("swagger-autogen")();

const doc = {
    info: {
        version: "1.0.0",
        title: "Aeolus API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: `aeolus.se`,
    basePath: "/api",
    schemes: ["http", "https"],
    consumes: ["application/json"],
    produces: ["application/json"],
    tags: [
        {
            name: "User",
            description: "Endpoints"
        },
        {
            name: "Simulator",
            description: "It's a simulator..."
        }
    ],
    securityDefinitions: {
        apiKeyAuth: {
            type: "apiKey",
            in: "header", // can be "header", "query" or "cookie"
            name: "X-API-KEY", // name of the header, query parameter or cookie
            description: "any description..."
        }
    }
};

if (process.env.SWAGGER_FILE === undefined) {
    throw new Error(
        "Swagger outputfile cannot be undefined. Please specify a value to the enviroment variable 'SWAGGER_FILE'."
    );
}

const outputFile = `./dist/${process.env.SWAGGER_FILE}`;
const endpointsFiles = ["./src/main.ts"];

console.log(`outputfile is: "${outputFile}"`);

swaggerAutogen(outputFile, endpointsFiles, doc);
