if (process.env.NODE_ENV === "development") {
    require("dotenv").config();
}

import swaggerAutogen from "swagger-autogen";
import { Household, DashboardCardType } from "./db/models/household";

const household = new Household({
    area: 120,
    baseConsumption: 500,
    battery: { maxCapacity: 1000 },
    blackout: false,
    buyRatioUnderProduction: 0.5,
    consumptionSpike: { AmplitudeMean: 2300, AmplitudeVariance: 400, DurationMean: 40, DurationVariance: 10 },
    dashboard: { Cards: [DashboardCardType.Buffer, DashboardCardType.Consumption] },
    heatingEfficiency: 0.4
});

const doc = {
    info: {
        version: "1.0.0",
        title: "Aeolus API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: `aeolus.se`,
    basePath: "/api",
    schemes: ["http", "https"],
    consumes: ["application/json"],
    produces: ["application/json"],
    tags: [
        {
            name: "User",
            description: "Endpoints"
        },
        {
            name: "Simulator",
            description: "It's a simulator..."
        }
    ],
    securityDefinitions: {
        apiKeyAuth: {
            type: "apiKey",
            in: "header", // can be "header", "query" or "cookie"
            name: "X-API-KEY", // name of the header, query parameter or cookie
            description: "any description..."
        }
    },
    definitions: {
        Test: {
            foo: "bar",
            date: "today"
        }
        //Household: household
    }
};

console.log(JSON.stringify(doc));

if (process.env.SWAGGER_FILE === undefined) {
    throw new Error(
        "Swagger outputfile cannot be undefined. Please specify a value to enviroment variable 'SWAGGER_FILE'."
    );
}

const outputFile = process.env.SWAGGER_FILE;
const endpointsFiles = ["./main.js"];

console.log(`outputfile is: "${outputFile}"`);

swaggerAutogen(outputFile, endpointsFiles, doc);
